apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"azure.workload.identity/use":"true"},"name":"busybox-secrets-store-inline-wi","namespace":"default"},"spec":{"containers":[{"command":["/bin/sleep","10000"],"image":"registry.k8s.io/e2e-test-images/busybox:1.29-4","name":"busybox","volumeMounts":[{"mountPath":"/mnt/secrets-store","name":"secrets-store01-inline","readOnly":true}]}],"serviceAccountName":"workload-identity-sa","volumes":[{"csi":{"driver":"secrets-store.csi.k8s.io","readOnly":true,"volumeAttributes":{"secretProviderClass":"azure-kvname-wi"}},"name":"secrets-store01-inline"}]}}
    creationTimestamp: "2024-09-19T15:15:33Z"
    labels:
      azure.workload.identity/use: "true"
    name: busybox-secrets-store-inline-wi
    namespace: default
    resourceVersion: "1179636"
    uid: 970d5ffe-c039-49ac-8ff0-39b11818e4f5
  spec:
    containers:
    - command:
      - /bin/sleep
      - "10000"
      env:
      - name: AZURE_CLIENT_ID
        value: dcfc2c05-b940-432f-aa53-5564b87e8ed0
      - name: AZURE_TENANT_ID
        value: 5cdd50a9-c23b-4349-b4cb-7d72d5737ec8
      - name: AZURE_FEDERATED_TOKEN_FILE
        value: /var/run/secrets/azure/tokens/azure-identity-token
      - name: AZURE_AUTHORITY_HOST
        value: https://login.microsoftonline.com/
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      imagePullPolicy: IfNotPresent
      name: busybox
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /mnt/secrets-store
        name: secrets-store01-inline
        readOnly: true
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-vkxb5
        readOnly: true
      - mountPath: /var/run/secrets/azure/tokens
        name: azure-identity-token
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: aks-nodepool1-29430503-vmss000000
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: workload-identity-sa
    serviceAccountName: workload-identity-sa
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: azure-kvname-wi
      name: secrets-store01-inline
    - name: kube-api-access-vkxb5
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
    - name: azure-identity-token
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            audience: api://AzureADTokenExchange
            expirationSeconds: 3600
            path: azure-identity-token
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-09-19T15:15:38Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2024-09-19T15:15:34Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-09-23T08:09:26Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-09-23T08:09:26Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-09-19T15:15:33Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://8a0f0b55349ebc013c72067b4aa8f6a8e6171b65a8cbb3405a26c7dbb4cb764d
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      imageID: registry.k8s.io/e2e-test-images/busybox@sha256:2e0f836850e09b8b7cc937681d6194537a09fbd5f6b9e08f4d646a85128e8937
      lastState:
        terminated:
          containerID: containerd://7d61b87bc24c7c9a35a72a04ebbf5cd8042959486204991710137db1e070375a
          exitCode: 0
          finishedAt: "2024-09-23T08:09:24Z"
          reason: Completed
          startedAt: "2024-09-23T05:22:44Z"
      name: busybox
      ready: true
      restartCount: 32
      started: true
      state:
        running:
          startedAt: "2024-09-23T08:09:25Z"
    hostIP: 10.224.0.4
    hostIPs:
    - ip: 10.224.0.4
    phase: Running
    podIP: 10.244.0.16
    podIPs:
    - ip: 10.244.0.16
    qosClass: BestEffort
    startTime: "2024-09-19T15:15:34Z"
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2024-09-19T14:24:27Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "196"
    uid: 95c4b082-7f17-42cc-8866-32b917a065d8
  spec:
    clusterIP: 10.0.0.1
    clusterIPs:
    - 10.0.0.1
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
